### ISSUE TITLE
TIL 상세 페이지

### ISSUE THREAD

**Issue by zwan2** [slightly-spring/imgo#14]
In GitLab by @zwan2 on Oct 31, 2021, 24:58

### Todo

- [x]  TIL 관련 정보 출력
- [x]  TIL 삭제 기능
- [x]  라이벌 등록 기능
- [ ]  TIL 작성 완료 모달
- [ ]  조회수 기능
- [ ]  추천 기능
- [ ]  뱃지 관련 기능 - 서비스 참조 이슈
- [ ]  수정 기능
- [ ]  댓글기능

**Comment by zwan2** [comment]
In GitLab by @zwan2 on Oct 31, 2021, 24:59

mentioned in merge request !29
